parameters:
    rohea_file_storage.class: FileStorage\FileStorage
    rohea_file_storage.adapter.class: 

    # Default GridFS config
    rohea_file_storage.mongo.server: "mongodb://localhost:27017"
    rohea_file_storage.mongo.options:
        connect: true
    rohea_file_storage.mongodb.name: "test_database"
    rohea_file_storage.gridfs.prefix: "fs" #Default
    
services:
    rohea_file_storage:
        class: %rohea_file_storage.class%
        arguments: [@rohea_file_storage.adapter.local]



    rohea_file_storage.adapter.gridfs:
        class: FileStorage\Adapter\GridFS
        arguments: [@rohea_file_storage.gridfs]
        
    rohea_file_storage.adapter.local:
        class: FileStorage\Adapter\Local
        arguments: ["/tmp"]

        
    # Default Mongo and gridfs stuff                
    rohea_file_storage.mongo:
        class: Mongo
        arguments: [%rohea_file_storage.mongo.server%, %rohea_file_storage.mongo.options%]
    rohea_file_storage.mongodb:
        class: MongoDB
        arguments: [@rohea_file_storage.mongo, %rohea_file_storage.mongodb.name%]
    rohea_file_storage.gridfs:
        class: MongoGridFS
        arguments: [@rohea_file_storage.mongodb, %rohea_file_storage.gridfs.prefix%]
        

